#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Sep 02 12:52:23 -03 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto e1505db9b8e84491b2a2a28a18d05acb --incr --debug typical --relax --mt 8 -L mito -L secureip --snapshot test_bench_behav mito.test_bench -log elaborate.log"
xelab -wto e1505db9b8e84491b2a2a28a18d05acb --incr --debug typical --relax --mt 8 -L mito -L secureip --snapshot test_bench_behav mito.test_bench -log elaborate.log

